### 카테고리별 최저가 상품 조회
GET http://localhost:8080/api/products/category/lowest-prices

### 단일 브랜드의 전체 카테고리 상품 구매 시 최저가 조회
GET http://localhost:8080/api/products/brand/1/lowest-total-price

### 특정 카테고리에서 최저가 및 최고가 상품 조회
GET http://localhost:8080/api/products/category/상의/price-range

### 상품 추가
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "category": {
    "id": 1,
    "name": "상의"
  },
  "brand": {
    "id": 1,
    "name": "A"
  },
  "price": 12000
}

### 상품 수정
PUT http://localhost:8080/api/products/1
Content-Type: application/json

{
  "category": {
    "id": 1,
    "name": "상의"
  },
  "brand": {
    "id": 1,
    "name": "A"
  },
  "price": 13000
}

### 상품 삭제
DELETE http://localhost:8080/api/products/1

###






