spring:
    datasource:
        generate-unique-name: false
        url: jdbc:h2:mem:test
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
    sql:
        init:
            mode: always

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                show_sql: true
