### 브랜드 추가
POST http://localhost:8080/private-api/brands
Content-Type: application/json

{
  "name": "New Brand"
}

### 브랜드 수정
PUT http://localhost:8080/private-api/brands/10
Content-Type: application/json

{
  "name": "Updated Brand Name"
}

### 브랜드 삭제
DELETE http://localhost:8080/private-api/brands/10

###



