### 카테고리별 최저가 상품 조회
GET http://localhost:8080/api/products/category/lowest-prices

### 단일 브랜드의 전체 카테고리 상품 구매 시 최저가 조회
GET http://localhost:8080/api/products/brand/lowest-prices

### 특정 카테고리에서 최저가 및 최고가 상품 조회
GET http://localhost:8080/api/products/category/price-range?categoryName=모자

###
